name: Expo Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      expo_user:
        description: 'Expo user name'
        required: true
        default: 'TheEdge'
      expo_password:
        description: 'Expo Password'
        required: true
        default: 'reactiscool'
jobs:
  publish:
    name: Install and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        #with:
            #node-version: 15.x
      - uses: expo/expo-github-action@v5
        with:
            #expo-version: 4.x
            expo-username: ${{ github.event.inputs.expo_user}}
            expo-password: ${{ github.event.inputs.expo_password}}
      - run: git clone git://github.com/kkaefer/node-zlib.git && cd node-zlib && ./configure && make #zlib-bindings
      - run: npm install
      - run: npm install zlib zlib-sync react-zlib-js pdfkit
      - run: expo login -u TheEdge -p reactiscool
      - run: export NODE_OPTIONS="--max-old-space-size=4096" && expo publish  --target bare --non-interactive # --target managed
        
